---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSClusterStaticIdentity
metadata:
  name: aws-cluster-identity
spec:
  secretRef: $AWS_CREDENTIALS_SECRET_NAME
  allowedNamespaces: {}

---
apiVersion: hmc.mirantis.com/v1alpha1
kind: Credential
metadata:
  name: $AWS_CREDENTIAL_NAME
  namespace: $HMC_NAMESPACE
spec:
  description: "Basic AWS credentials"
  identityRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
    kind: AWSClusterStaticIdentity
    name: aws-cluster-identity