---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: helm-repsitory
  namespace: $HMC_NAMESPACE
spec:
  interval: 10m0s
  path: ./management/helm-repository
  prune: true
  sourceRef:
    kind: GitRepository
    name: $FLUX_GIT_REPO_NAME