---
apiVersion: v1
kind: Namespace
metadata:
  name: $HMC_NAMESPACE
  labels:
    product.mirantis.com: hmc

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: $FLUX_GIT_REPO_NAME
  namespace: $HMC_NAMESPACE
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/$GITHUB_USERNAME/$GITHUB_REPO_NAME.git

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hmc-system
  namespace: $HMC_NAMESPACE
spec:
  interval: 10m0s
  path: ./management/hmc-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: $FLUX_GIT_REPO_NAME