---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: provider-credentials
  namespace: $HMC_NAMESPACE
spec:
  interval: 10m0s
  path: ./credentials
  prune: true
  sourceRef:
    kind: GitRepository
    name: $FLUX_GIT_REPO_NAME
    namespace: $HMC_NAMESPACE