---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureClusterIdentity
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move-hierarchy: "true"
  name: azure-cluster-identity
  namespace: hmc-system
spec:
  allowedNamespaces: {}
  clientID: $AZURE_SP_APP_ID
  clientSecret:
    name: $AZURE_CREDENTIALS_SECRET_NAME
    namespace: $HMC_NAMESPACE
  tenantID: $AZURE_SP_TENANT_ID
  type: ServicePrincipal

---
apiVersion: hmc.mirantis.com/v1alpha1
kind: Credential
metadata:
  name: $AZURE_CREDENTIAL_NAME
  namespace: $HMC_NAMESPACE
spec:
  description: "Basic Azure credentials"
  identityRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureClusterIdentity
    name: azure-cluster-identity
    namespace: $HMC_NAMESPACE